Donate/Controllers/ManageBeritaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Donate.Models;

namespace Donate.Controllers
{
    public class ManageBeritaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ManageBerita
        public ActionResult Index()
        {
            if (TempData["gagalHapus"] != null)
            {
                ViewBag.gagalHapus = TempData["gagalHapus"].ToString();
            }
            if (TempData["berhasilHapus"] != null)
            {
                ViewBag.berhasilHapus = TempData["berhasilHapus"].ToString();
            }

            var berita = db.Berita;

            return View(berita.ToList());
        }

        // GET: ManageBerita/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Berita berita = db.Berita.Find(id);
            if (berita == null)
            {
                return HttpNotFound();
            }
            return View(berita);
        }

        [Route("ManageBerita/Tampil/{id}")]
        [HttpPost]
        public ActionResult Tampil(Guid id)
        {
            var data = db.Berita.Find(id);
            if (data != null)
            {
                if (data.IsActive)
                    data.IsActive = false;
                else
                    data.IsActive = true;

                db.Entry(data).State = EntityState.Modified;
                db.SaveChanges();
            }

            return Json(JsonRequestBehavior.AllowGet);
        }

        // GET: ManageBerita/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManageBerita/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,Title,Ikhtisar,Content,ImageName,Image,IsActive,LastModified")] Berita berita)
        {
            string path = Server.MapPath("~/ImageBerita/");
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
            var NameImage = "";

            if (berita.Image != null)
            {
                #region[extension validation]
                var listAllowExt = new List<string> { "jpg", "jpeg", "png" };
                var fileExt = Path.GetExtension(berita.Image.FileName).Substring(1);
                if(!listAllowExt.Contains(fileExt, StringComparer.OrdinalIgnoreCase))
                    ModelState.AddModelError("Image", string.Format("hanya diijinkan file gambar dengan type {0}.", String.Join(", ", listAllowExt)));
                #endregion

                #region[size validation]
                bool isValidSize = true;
                var vimg = new Bitmap(berita.Image.InputStream);
                if (vimg.Width < 790)
                    isValidSize = false;
                if(vimg.Height < 400)
                    isValidSize = false;

                if(!isValidSize)
                    ModelState.AddModelError("Image", "Gambar yang diijinkan minimal 790x400");
                #endregion

                #region[save image]
                NameImage = string.Format("{0}{1}", Guid.NewGuid().ToString(), Path.GetExtension(berita.Image.FileName));
                WebImage img = new WebImage(berita.Image.InputStream);
                if (img.Width > 790)
                    img.Resize(790, 400, false);
                img.Save(path + NameImage);
                #endregion
            }
            else
            {
                ModelState.AddModelError("Image", "Gambar harus diupload");
            }

            berita.IsActive = true;
            berita.ImageName = NameImage;
            berita.LastModified = DateTime.Now;
            if (ModelState.IsValid)
            {
                berita.Id = Guid.NewGuid();
                db.Berita.Add(berita);
                //db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            #region[remove image when fail save data]
            string fullPath = path + NameImage;
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            #endregion

            return View(berita);
        }

        // GET: ManageBerita/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Berita berita = db.Berita.Find(id);
            if (berita == null)
            {
                return HttpNotFound();
            }
            return View(berita);
        }

        // POST: ManageBerita/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Ikhtisar,Content,ImageName,Image,IsActive,LastModified")] Berita berita)
        {
            string path = Server.MapPath("~/ImageBerita/");
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
            var NameImage = "";

            if (berita.Image != null)
            {
                #region[remove old Image]
                string oldImage = path + berita.ImageName;
                if (System.IO.File.Exists(oldImage))
                {
                    System.IO.File.Delete(oldImage);
                }
                #endregion

                #region[extension validation]
                var listAllowExt = new List<string> { "jpg", "jpeg", "png" };
                var fileExt = Path.GetExtension(berita.Image.FileName).Substring(1);
                if (!listAllowExt.Contains(fileExt, StringComparer.OrdinalIgnoreCase))
                    ModelState.AddModelError("Image", string.Format("hanya diijinkan file gambar dengan type {0}.", String.Join(", ", listAllowExt)));
                #endregion

                #region[size validation]
                bool isValidSize = true;
                var vimg = new Bitmap(berita.Image.InputStream);
                if (vimg.Width < 790)
                    isValidSize = false;
                if (vimg.Height < 400)
                    isValidSize = false;

                if (!isValidSize)
                    ModelState.AddModelError("Image", "Gambar yang diijinkan minimal 790x400");
                #endregion

                #region[save image]
                NameImage = string.Format("{0}{1}", Guid.NewGuid().ToString(), Path.GetExtension(berita.Image.FileName));
                WebImage img = new WebImage(berita.Image.InputStream);
                if (img.Width > 790)
                    img.Resize(790, 400, false);
                img.Save(path + NameImage);
                #endregion

                berita.ImageName = NameImage;
            }

            berita.LastModified = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(berita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            #region[remove image when fail save data]
            string fullPath = path + NameImage;
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            #endregion

            return View(berita);
        }

        //// GET: ManageBerita/Delete/5
        //public ActionResult Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Berita berita = db.Berita.Find(id);
        //    if (berita == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(berita);
        //}

        //// POST: ManageBerita/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            string path = Server.MapPath("~/ImageBerita/");

            Berita berita = db.Berita.Find(id);
            string oldImage = path + berita.ImageName;
            db.Berita.Remove(berita);
            try
            {
                db.SaveChanges();
                if (System.IO.File.Exists(oldImage))
                {
                    System.IO.File.Delete(oldImage);
                }
                TempData["berhasilHapus"] = "Berhasil Hapus Data.";
            }
            catch (DbUpdateException)
            {
                TempData["gagalHapus"] = "Gagal Hapus, Data sudah digunakan";
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Donate/Views/ManageBerita/Create.cshtml
@model Donate.Models.Berita

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    var actionName = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString();
}

<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Dashboard">Home</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><i class="icon-list"></i><a href="/@controllerName">Berita</a></li>
    <li><i class="icon-angle-right"></i><i class="ui-icon-plus"></i><a href="/@controllerName/@actionName">Tambah Data</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Tambah Data Berita</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Create", "ManageBerita", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <fieldset>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="control-group error">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.EditorFor(model => model.Title)
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group hidden-phone">
                            @Html.LabelFor(model => model.Ikhtisar, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextAreaFor(model => model.Ikhtisar, new { @row = 4 })
                                @Html.ValidationMessageFor(model => model.Ikhtisar, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group hidden-phone">
                            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextAreaFor(model => model.Content, new { @class = "cleditor", @row = 3 })
                                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="Image">File input</label>
                            <div class="controls">
                                <input class="input-file uniform_on" id="Image" name="Image" type="file">
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="@Url.Action("Index")" class="btn btn-danger">
                                Batal
                            </a>
                        </div>
                    </fieldset>
                </div>
            }

        </div>
    </div><!--/span-->

</div><!--/row-->

Donate/Views/ManageBerita/Delete.cshtml
@model Donate.Models.Berita

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Berita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Donate/Views/ManageBerita/Details.cshtml
@model Donate.Models.Berita

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    var actionName = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString();
}


<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Dashboard">Home</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><i class="icon-list"></i><a href="/@controllerName">Berita</a></li>
    <li><i class="icon-angle-right"></i> <i class="ui-icon-plus"></i> <a href="/@controllerName/@actionName/@Model.Id">Details Data</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white zoom-in"></i><span class="break"></span>Details Data Berita</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Content)
                </dt>

                <dd>
                    @Html.Raw(Model.Content)
                </dd>

                <dt>
                    @Html.DisplayName("Gambar")
                </dt>

                <dd>
                    <img src="~/ImageBerita/@Model.ImageName" class="img-responsive img-rounded"  width="460" height="345" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastModified)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastModified)
                </dd>

            </dl>
            <p>
                <a href="@Url.Action("Edit", new { id = Model.Id})" class="btn btn-default">
                    Edit Data
                </a>
                <a href="@Url.Action("Index")" class="btn btn-danger">
                    Kembali
                </a>
            </p>

        </div>
    </div><!--/span-->

</div><!--/row-->

Donate/Views/ManageBerita/Edit.cshtml
@model Donate.Models.Berita

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    var actionName = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString();
}

<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Dashboard">Home</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><i class="icon-list"></i><a href="/@controllerName">Berita</a></li>
    <li><i class="icon-angle-right"></i><i class="ui-icon-plus"></i><a href="/@controllerName/@actionName/@Model.Id">Edit Data</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Edit Data Berita</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Edit", "ManageBerita", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <fieldset>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.ImageName)
                        @Html.HiddenFor(model => model.IsActive)
                        <div class="control-group error">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.EditorFor(model => model.Title)
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group hidden-phone">
                            @Html.LabelFor(model => model.Ikhtisar, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextAreaFor(model => model.Ikhtisar, new { @row = 4 })
                                @Html.ValidationMessageFor(model => model.Ikhtisar, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group hidden-phone">
                            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextAreaFor(model => model.Content, new { @class = "cleditor", @row = 3 })
                                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="Image">File input</label>
                            <div class="controls">
                                <input class="input-file uniform_on" id="Image" name="Image" type="file">
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "help-inline" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="@Url.Action("Index")" class="btn btn-danger">
                                Batal
                            </a>
                        </div>
                    </fieldset>
                </div>
            }

        </div>
    </div><!--/span-->

</div><!--/row-->

Donate/Views/ManageBerita/Index.cshtml
@model IEnumerable<Donate.Models.Berita>

@{
    ViewBag.Title = "Manage Berita";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
}
<style>
    .thumbnail {
        position: relative;
        width: 100px;
        height: 100px;
        overflow: hidden;
    }

        .thumbnail img {
            position: absolute;
            left: 50%;
            top: 50%;
            height: 100%;
            width: auto;
            -webkit-transform: translate(-50%,-50%);
            -ms-transform: translate(-50%,-50%);
            transform: translate(-50%,-50%);
        }
</style>


<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Dashboard">Home</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><i class="icon-list"></i> <a href="/@controllerName">Berita</a></li>
</ul>

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">Tambah data &nbsp;<i class="halflings-icon white plus"></i></a>
</p>
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white list-alt"></i><span class="break"></span>Data Berita</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table id="table" class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>
                            <i class="halflings-icon picture"></i>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ikhtisar)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>
                        <th>
                            @Html.DisplayName("Tgl Update")
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        var dateDiff = (DateTime.Today - item.LastModified.Date).TotalDays;
                        string date = (dateDiff == 0) ? "Today, " : (dateDiff == 1) ? "Yesterday, " : item.LastModified.ToShortDateString() + ", ";
                        <tr>
                            <td>
                                <div class="thumbnail">
                                    <img src="~/ImageBerita/@item.ImageName" alt="Image" />
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ikhtisar) ...
                            </td>
                            <td style="text-align: center;">
                                <input type="checkbox"
                                       class="js-check"
                                       data-role="@item.Id"
                                       @if (item.IsActive) { @("checked") } />

                            </td>
                            <td style="white-space:nowrap">
                                @date @item.LastModified.ToString("hh:mm tt", System.Globalization.CultureInfo.InvariantCulture)
                            </td>
                            <td class="center" style="white-space:nowrap">
                                <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-success">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                                <a class="btn btn-info" href="@Url.Action("Edit", new { id = item.Id })">
                                    <i class="halflings-icon white edit"></i>
                                </a>
                                <a class="btn btn-danger confirmation" href="@Url.Action("DeleteConfirmed", new { id = item.Id })">
                                    <i class="halflings-icon white trash"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div><!--/span-->

</div><!--/row-->


@section scripts
{
    <script>
        $(function () {
            let table = $('#table');
            table.on('click', '.js-check', function (e) {
                e.preventDefault();
                let checkbox = $(this);

                $.ajax({
                    url: '/ManageBerita/Tampil/' + checkbox.attr('data-role'),
                    method: 'POST',
                    success: function sweet() {
                        checkbox.prop("checked", !checkbox.prop("checked"));
                        swal('Selesai!', 'Success Update', 'success')
                            .then(function (isConfirm) {
                                if (isConfirm) {
                                    location.reload();
                                }
                            });
                    }
                })
            });
        });

        function sebSweetConfirm(originLink) {
            swal({
                title: 'Anda yakin?',
                text: "Akan menghapus data ini!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, hapus!',
                cancelButtonText: 'Batal',
                //closeOnConfirm: true,
                //closeOnCancel: true
            }).then(function (isConfirm) {
                if (isConfirm) {
                    window.location.href = originLink;
                }
            })
        }

        $('.confirmation').click(function (event) {
            event.preventDefault();
            var originLink = $(this).attr("href");
            sebSweetConfirm(originLink);
        });
    </script>

    @if (ViewBag.berhasilHapus != null)
    {
        <script>

            $(document).ready(function sweet() {
                swal('Selesai!', '@ViewBag.berhasilHapus', 'success');
            });

        </script>

    }
    @if (ViewBag.gagalHapus != null)
    {
        <script>

            $(document).ready(function sweet() {
                swal('Kesalahan!', '@ViewBag.gagalHapus', 'error');
            });

        </script>

    }
}